name: Install dependencies
description: Setup Node and install dependencies with NPM auth
inputs:
  
  node-auth-token:
    description: node auth token
    required:  true
  
  node-version:
    description: node version
    required: true
    default: "20"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org" # Or your private registry

    - name: Authenticate with NPM
      shell: bash
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ inputs.node-auth-token }}" > ~/.npmrc

    - name: Install dependencies
      shell: bash
      run: npm ci
