# This is a basic workflow to help you get started with Actions

name: Build and test user api

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      environment:
        description: app environment
        required: true
        type: string
 
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # install all depedencies from setup-app
      - uses: ./.github/actions/setup-app
        with:
          node-auth-token: ${{ secrets.NODE_AUTH_TOKEN }}

      # build app
      - name: Build app
        run: npm run build

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:

     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # install all depedencies from setup-app
      - uses: ./.github/actions/setup-app

      - name: run tests
        run: npm run test
