name: Dev Pipeline

on:
  push:
    branches: [ dev ]

jobs:
  
   ci:
    name: Build and run test in Development
    uses: ./.github/workflows/ci.yml
    with:
      environment: dev
   docker:
      name: Build and push image
      needs: ci
      uses: ./.github/workflows/docker-build-push.yml
      
      with:
        branch: main
        image_name: marcogjunior83/user-api
        environment: development
      secrets:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}  