name: Dev Pipeline

on:
  push:
    branches: [ dev ]

jobs:
   build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      environment: stage
   deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: prd
    steps:
      - run: echo "Deploying to Development..."
  