name: Dev Pipeline

on:
  push:
    branches: [ dev ]

jobs:
   ci:
    name: build-and-test
    uses: ./.github/workflows/ci.yml
    with:
      environment: stage
   deploy:
    needs: ci
    runs-on: ubuntu-latest
    environment:
      name: prd
    steps:
      - run: echo "Deploying to Development..."
  