name: Dev Pipeline

on:
  push:
    branches: [ dev ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: dev
  test:
    uses: ./.github/workflows/test.yml
    with:
      environment: dev
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - run: echo "Deploying to DEV..."