name: Dev Pipeline

on:
  push:
    branches: [ dev ]

jobs:
   build-and-test:
    uses: ./.github/workflows/ci.yml
    with:
      environment: dev
   deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
  
    steps:
      - run: echo "Deploying to Development..."
  