name: Dev Pipeline

on:
  push:
    branches: [ dev ]

jobs:
  call-ci:
    uses: ./.github/workflows/ci.yml
    with:
      environment: dev
      
  deploy:
    runs-on: ubuntu-latest
    needs: call-ci
    environment:
      name: dev
    steps:
      - run: echo "Deploying to DEV..."