name: Dev Pipeline

on:
  push:
    branches: [ dev ]

jobs:
   build-and-test:
    uses: ./.github/workflows/ci.yml
    with:
      environment: dev
   update-docker-image:
      needs: build-and-test
      uses: ./.github/workflows/docker-build-push.yml
      with:
        branch: main
        image_name: https://hub.docker.com/repositories/marcogjunior83
        environment: development