name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      image_name:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check if secrets are defined
        run: |
          if [ -z "${{secrets.DOCKER_USERNAME }}" ] || [ -z "${{secrets.DOCKER_PASSWORD }}" ]; then
            echo "❌ Docker secrets are not set."
            exit 1
          else
            echo "✅ Docker secrets appear to be set."
          fi
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set vars
        id: vars
        run: |
          echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Debug vars
        run: |
          echo "Branch: ${{ steps.vars.outputs.branch }}"
          echo "SHA: ${{ steps.vars.outputs.short_sha }}"
          
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ inputs.image_name }}:${{ steps.vars.outputs.branch || 'dev' }}
            ${{ inputs.image_name }}:${{ steps.vars.outputs.short_sha || 'latest' }}
            ${{ inputs.image_name }}:latest
