name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
     
      image_name:
        required: true
        type: string
     
     
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true

jobs:
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check if secrets are defined
        run: |
          if [ -z "${{secrets.DOCKER_USERNAME }}" ] || [ -z "${{secrets.DOCKER_TOKEN }}" ]; then
            echo "❌ Docker secrets are not set."
            exit 1
          else
            echo "✅ Docker secrets appear to be set."
          fi
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Generate Docker Tag
        id: tag
        run: |
          # Sanitize branch name
          BRANCH="${{ github.head_ref || github.ref_name }}"
          BRANCH_SAFE=$(echo $BRANCH | sed 's|/|-|g')

          # Short SHA
          SHORT_SHA="${GITHUB_SHA::7}"
          echo "tag=${BRANCH_SAFE}-${SHORT_SHA}" >> $GITHUB_OUTPUT
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ inputs.image_name }}:${{ steps.tag.outputs.tag }}
            
