name: Production Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: prd
  test:
    uses: ./.github/workflows/test.yml
    with:
      environment: prd
      
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: prd
    steps:
      - run: echo "Deploying to Production..."