name: Production Pipeline

on:
  push:
    branches: [ main ]

jobs:
  call-ci:
    uses: ./.github/workflows/ci.yml
    with:
      environment: prd
      
  deploy:
    runs-on: ubuntu-latest
    needs: call-ci
    environment:
      name: prd
    steps:
      - run: echo "Deploying to Production..."