name: Production Pipeline

on:
  push:
    branches: [ main ]

jobs:
   build-and-test:
    uses: ./.github/workflows/ci.yml
    with:
      environment: stage
   deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: prd
    steps:
      - run: echo "Deploying to Production..."