name: Production Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  
   ci:
    name: Build and run test in Production
    uses: ./.github/workflows/ci.yml
    with:
      environment: prd
   deploy:
    needs: ci
    runs-on: ubuntu-latest
  
    steps:
      - run: echo "Deploying to Production..."