name: Stage Pipeline

on:
  push:
    branches: [ stage ]

jobs:
  build-and-test:
    uses: ./.github/workflows/ci.yml
    with:
      environment: stage
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
   
    steps:
      - run: echo "Deploying to Stage..."