name: Stage Pipeline

on:
  push:
    branches: [ stage ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: stage
  test:
    uses: ./.github/workflows/test.yml
    with:
      environment: stage
      
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: stage
    steps:
      - run: echo "Deploying to Stage..."