name: Stage Pipeline

on:
  push:
    branches: [ stage ]

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
    with:
      environment: stage
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: stage
    steps:
      - run: echo "Deploying to Stage..."