name: Stage Pipeline

on:
  pull_request:
    branches: [ stage ]

jobs:
  ci:
    name: Build and run test in stage
    uses: ./.github/workflows/ci.yml
    with:
      environment: stage
  deploy:
    needs: ci
    runs-on: ubuntu-latest
   
    steps:
      - run: echo "Deploying to Stage..."