name: Stage Pipeline

on:
  push:
    branches: [ stage ]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      environment: stage
  deploy:
    needs: ci
    runs-on: ubuntu-latest
    environment:
      name: stage
    steps:
      - run: echo "Deploying to Stage..."