name: Stage Pipeline

on:
  push:
    branches: [ stage ]

jobs:
  call-ci:
    uses: ./.github/workflows/ci.yml
    with:
      environment: stage
      
  deploy:
    runs-on: ubuntu-latest
    needs: call-ci
    environment:
      name: stage
    steps:
      - run: echo "Deploying to Stage..."